title = "Kubernetes Community Days"
disableKinds = ["section", "taxonomy", "taxonomyTerm"]

[params]
description = "A series of conferences devoted to the Kubernetes ecosystem"
fontawesomeversion = "5.8.1"
sansseriffont = "Lato"

[[params.fonts]]
name = "Lato"
sizes = [300,400,600,700]

[params.social.twitter]
handle = "cloudnativedays"
link   = "https://twitter.com/cloudnativedays"
color  = "twitter-blue"

[params.social.facebook]
link = "https://facebook.com/cloudnativedays"
color = "facebook-blue"
