title = "Kubernetes Community Days"
disableKinds = ["section", "taxonomy", "taxonomyTerm"]

[params]
description = "A series of conferences devoted to the [Kubernetes](https://kubernetes.io) ecosystem"
fontawesomeversion = "5.8.1"
sansseriffont = "Lato"
info = """
**Kubernetes Community Days** are community-organized events that gather adopters and technologists from open source and cloud native communities to learn, collaborate, and network to further advancement in cloud native computing.

Backed by the [Cloud Native Computing Foundation](https://cncf.io), which hosts Kubernetes, community-run events are meant to provide additional opportunities for speakers, practitioners, and end users to come together. Kubernetes Community Days will be run by local community members. Each event brings its own local flair, culture, diversity, and authenticity.
"""

[params.logos]
hero = "kubernetes-community-days.png"

[[params.fonts]]
name = "Lato"
sizes = [300,400,600,700]

[params.social]
twitter = "https://twitter.com/cloudnativedays"
facebook = "https://facebook.com/cloudnativedays"
