title = "Cloud Native Days"
disableKinds = ["section", "taxonomy", "taxonomyTerm"]

[params]
description = "A series of conferences devoted to the Cloud Native landscape"
fontawesomeversion = "5.8.1"
sansseriffont = "Lato"

[[params.fonts]]
name = "Lato"
sizes = [300,400,600,700]

[params.social.twitter]
link = "https://twitter.com/cloudnativedays"
color = "twitter-blue"

[params.social.facebook]
link = "https://facebook.com/cloudnativedays"
color = "facebook-blue"
