title = "Kubernetes Community Days"
disableKinds = ["taxonomy", "taxonomyTerm"]
baseURL = "https://kubernetescommunitydays.org/"

[params]
description = "A series of conferences devoted to the cloud native and [Kubernetes](https://kubernetes.io) ecosystem"
fontawesomeversion = "5.8.1"
sansseriffont = "Lato"
logo = "kubernetes-community-days.png"

[[params.fonts]]
name = "Lato"
sizes = [300,400,600,700]

[params.social]
twitter = "https://twitter.com/cloudnativefdn"

[[menu.navbar]]
name = "Events"
url = "/events"
weight = 1

[[menu.navbar]]
name = "About"
url = "/about"
weight = 2

[[menu.navbar]]
name = "Organizing"
url = "/organizing"
weight = 3

[[menu.navbar]]
name = "Speaking"
url = "/speaking"
weight = 4
