title = "Kubernetes Community Days"
disableKinds = ["section", "taxonomy", "taxonomyTerm"]
baseURL = "https://kubernetes-community-days.netlify.com"

[params]
description = "A series of conferences devoted to the [Kubernetes](https://kubernetes.io) ecosystem"
fontawesomeversion = "5.8.1"
sansseriffont = "Lato"
logo = "kubernetes-community-days.png"

[[params.fonts]]
name = "Lato"
sizes = [300,400,600,700]

[params.social]
twitter = "https://twitter.com/cloudnativedays"
facebook = "https://facebook.com/cloudnativedays"
