backend:
  name: git-gateway
  branch: master
publish_mode: editorial_workflow
media_folder: static/img
public_folder: /img
collections:
- name: events
  label: Events
  folder: content/events
  create: true
  slug: "{{year}}-{{slug}}"
  fields:
  - {label: "Title", name: "title", widget: "string"}
  - {label: "Tag", name: "tag", widget: "string"}
  - {label: "Date", name: "date", widget: "datetime"}
  - {label: "Body", name: "body", widget: "markdown"}
